# Generated by Django 4.2.7 on 2025-05-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
