# Generated by Django 4.2.7 on 2025-05-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_cheque_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='approved',
        ),
        migrations.AddField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
